#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: jacking75

# Short bio or description (displayed in the header)
description: online game server programmer <br> GameServer, Network, C++, C#, Go  <br> 후원하기 https://toss.me/jacking75  

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: http://i64.tinypic.com/2ip8io.png

#
# Flags below are optional
#

timezone: Asia/Seoul

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: 
  email: jacking75@gmail.com
  facebook: 
  flickr: 
  github: jacking75
  instagram: 
  linkedin: 흥배-최-aa024344
  pinterest: 
  rss: https://jacking75.github.io/feed.xml
  twitter: jacking75
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"

# Your disqus shortname, entering this will enable commenting on posts
disqus: jacking75

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-106924101-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://jacking75.github.io

# If you're hosting your site at a Project repository on GitHub pages 
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

future: true
markdown: kramdown
highlighter: rouge
permalink: /:title/

kramdown:
  input: GFM
  hard_wrap: false
    
# The release of Jekyll Now that you're using
version: v3.0.2

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :compressed # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-redirect-from
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

paginate: 10
